serverFiles:
  alerting_rules.yml:
    groups:
    - name: Nodes monitoring
      rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance down (instance {{ $labels.instance }})"
          description: "A Prometheus target has disappeared. The instance is down or an exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"