serverFiles:
  prometheus.yml:
    rule_files:
    - /etc/config/alerting_rules.yml
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090

    - job_name: 'demo'
      metrics_path: '/metrics'
      static_configs:
      - targets: ['demo:8080']
        labels:
          hostname: int-prd-vmm-01

    - job_name: 'exporters-internal'
      honor_labels: true
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_probe]
          action: keep
          regex: exporter
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: (.+?)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
          replacement: __param_$1
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_phase]
          regex: Pending|Succeeded|Failed|Completed
          action: drop

# server:
#   retention: "10d"
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - 10.103.174.40:9093

# server:
#   retention: "10d"
#   alertmanagers:
#   - kubernetes_sd_configs:
#     - role: pod
#     relabel_configs:
#     - source_labels: [__meta_kubernetes_namespace]
#       separator: ;
#       regex: monitoring
#       replacement: $1
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_label_app]
#       separator: ;
#       regex: prometheus
#       replacement: $1
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_label_component]
#       separator: ;
#       regex: alertmanager
#       replacement: $1
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_probe]
#       separator: ;
#       regex: .*
#       replacement: $1
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_container_port_number]
#       separator: ;
#       regex: "9093"
#       replacement: $1
#       action: keep
      

prometheus-pushgateway:
  enabled: false
