FROM php:7.4-cli-alpine

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

RUN apk add --no-cache procps

COPY app/backend/ /app

WORKDIR /app

CMD [ "php", "-S", "0.0.0.0:5000", "-c", "php.ini" ]
