adminUser: admin
admin:
  existingSecret: "${admin_existing_secret}"
  userKey: ${admin_user_key}
  passwordKey: ${admin_password_key}
  
datasources: 
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://${prometheus_svc}
      access: proxy
      isDefault: true

persistence:
  type: pvc
  enabled: true
  size: 2Gi
  storageClassName: gp2

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts: ${hosts}