server:
  ingress:
    enabled: true
    hosts: ${hosts}
    annotations:
      kubernetes.io/ingress.class: nginx
      # nginx.ingress.kubernetes.io/auth-realm: Authentication Required - admin
      # nginx.ingress.kubernetes.io/auth-secret: prometheus-auth
      # nginx.ingress.kubernetes.io/auth-type: basic

  persistentVolume:
    enabled: true
    size: 2Gi
    storageClass: gp2

prometheus-pushgateway:
  enabled: false